# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255, verbose_name='Ip адрес')),
                ('referrer', models.CharField(max_length=255, verbose_name='Referrer')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Referrer',
                'verbose_name_plural': 'Referrers',
            },
        ),
    ]
